# ─────────────────────────────────────────────────────────────────────────────
# 프로젝트 루트에 반드시 'config.yaml' 라는 이름으로 저장해야 Hugo가 인식합니다.
# ─────────────────────────────────────────────────────────────────────────────

# 1) 최상위 설정 (Hugo가 반드시 인식하는 부분)
baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Chanyu Moon"
theme: "hugo-profile"

# Hugo가 어떤 형식으로 결과물을 내보낼지 지정합니다.
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - RSS

enableRobotsTXT: true

# 아래 pagination 은 Hugo 0.109+ 부터 [pagination] 블록 대신 'paginate' 를 더 권장하기도 합니다.
# 그러나 0.109 이후 버전이라면, 아래처럼 pagerSize 설정을 인식할 수 있습니다.
pagination:
  pagerSize: 3

markup:
  goldmark:
    renderer:
      unsafe: true

# ─────────────────────────────────────────────────────────────────────────────
# 2) 메뉴(네비게이션 바) 설정 (Hugo가 인식하는 키는 'menu' 소문자입니다.)
# ─────────────────────────────────────────────────────────────────────────────
menu:
  main:
    - identifier: blog
      name: "Blog"
      title: "Blog posts"
      url: "/blogs"
      weight: 1

    # (만약 드롭다운 메뉴가 필요하면 아래와 같이 parent를 지정)
    # - identifier: dropdown
    #   name: "Dropdown"
    #   title: "Example dropdown menu"
    #   weight: 3
    # - identifier: dropdown1
    #   name: "Example 1"
    #   title: "example dropdown 1"
    #   url: "/#"
    #   parent: "dropdown"
    #   weight: 1
    # - identifier: dropdown2
    #   name: "Example 2"
    #   title: "example dropdown 2"
    #   url: "/#"
    #   parent: "dropdown"
    #   weight: 2

# ─────────────────────────────────────────────────────────────────────────────
# 3) params: 아래에 hugo-profile 테마 전용 옵션들을 배치해야 합니다.
# ─────────────────────────────────────────────────────────────────────────────
params:
  customScripts: "css/index.css"  # 커스텀 CSS 파일 경로 (assets/css/custom.css)
  title: "Chanyu Moon"
  description: "Log of Chanyu Moon."
  favicon: "/images/cym-logo.png"  # 로고 파일을 favicon으로 사용합니다.

  # Bootstrap CDN 사용 여부 (false로 두면 themes 내 로컬 리소스를 사용)
  useBootstrapCDN: false

  # mathjax, animate 는 테마가 상태를 체크해서 필요할 때만 스크립트를 로딩합니다.
  mathjax: false
  animate: true

  # ───────────────────────────────────────────────────────────────────────────
  # 3-1) Navbar (헤더) 설정
  # ───────────────────────────────────────────────────────────────────────────
  navbar:
    align: "ms-auto"          # 왼쪽 정렬: ms-auto, 중앙: mx-auto, 오른쪽: me-auto
    brandLogo: "/images/cym-logo.png"  # left 로고 파일 (기본값은 favicon)
    # showBrandLogo: false    # 로고 표시 여부
    brandName: "Chanyu Moon"
    disableSearch: false

    stickyNavBar:
      enable: true
      showOnScrollUp: true

    enableSeparator: false

    # 테마가 제공하는 "About / Experience / Projects / ..." 메뉴를 자동으로 만들어 줍니다.
    # false 로 바꾸면 해당 메뉴 항목이 네비게이션에서 사라집니다.
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # ───────────────────────────────────────────────────────────────────────────
  # 3-2) Hero 섹션 (첫 화면 상단 인트로 텍스트)
  # ───────────────────────────────────────────────────────────────────────────
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Chanyu Moon."
    subtitle: "I'm a graduate researcher."
    content: "As a Researcher, I'm Interested in Natural & Artificial Intelligence and question how they can be coaporated to solve real-world problems."
    # \item My research goal is to \textbf{understand Natural and Artificial Intelligence(AI) more deeper to solve and help human society}.
    #     \item \textbf{Using Artificial Intelligence to understand Natual Intelligence}
    #     \begin{itemize}
    #     \item To understand the brain, we need to modulate it and analyze its dynamics. Artificial Intellegence can help us to process the complex brain dynamics to understand the brain. 
    #     \end{itemize}
    #     \item \textbf{Enhancing Artificial Intelligence based on our understanding of Natural Intelligence}
    #     \begin{itemize}
    #     \item If we understand the brain more deeply, we can adapt this to enhance artificial intelligence.
    #     \end{itemize}
    #     \item My current research is focused on:
    #     \begin{itemize}
    #         \item \textbf{Understanding of Natural Intelligence}: Explainable brain circuit models.
    #         \item \textbf{Artificial Intelligence for Medical Domain}: Deep brain stimulation for Parkinson's Disease Patient, Chest X-ray classification.
    #     \end{itemize}
    image: "/images/headshot.jpg"

    bottomImage:
      enable: true

    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false

    socialLinks:
      fontAwesomeIcons:
        - icon: "fab fa-github"
          url: "https://github.com/ChanyuMoon"
        - icon: "fab fa-linkedin"
          url: "https://www.linkedin.com/in/chanyu-moon-714727229/"
        - icon: "fas fa-graduation-cap"
          url: "https://scholar.google.com/citations?hl=ko&user=l9m2FnQAAAAJ&view_op=list_works&gmla=AOv-ny9DsJGv4hvrmkwzkQ1cEgpMwCDR970UmxZ3N7SV3a4Dlm_iVlBUXitqVo5yJLbwvRNc-Mauupg--xHyhdqGDeWMOyOZKwUoq1-PnUErZTnulV4-h1cMdQ"



      # customIcons:
      #   - icon: "/fav.png"
      #     url: "https://example.com"

  # ───────────────────────────────────────────────────────────────────────────
  # 3-3) About 섹션
  # ───────────────────────────────────────────────────────────────────────────
  about:
    enable: false
    title: "About Me"
    image: "/images/headshot.jpg"    # 실제로 static/images/me.png 파일이 있어야 합니다.
    content: |-
      I am a graduate researcher who is interested in Natual & Artificial Intelligence.
      I have a background in electrical engineering and computer science and 
      I am currently working as a graduate researcher at DGIST in Daegu, South Korea. 

    skills:
      enable: false  # true로 바꾸면 기술 목록이 표시됩니다.
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "MatLab"


  # ───────────────────────────────────────────────────────────────────────────
  # 3-4) Experience 섹션
  # ───────────────────────────────────────────────────────────────────────────
  experience:
    enable: true
    title: "Publications"
    subtitle: "*: Equal contribution, †: Corresponding author"
    items:
      - company: "International Conference"
        publications:
          - job: "OFF-CLIP: Improving Normal Detection Confidence in Radiology CLIP with Simple Off-Diagonal Term Auto-Adjustment"
            image: "/images/IC1_offclip_figure.png"
            author: "Junhyun Park*, <ins>Chanyu Moon</ins>*, Donghwan Lee, Kyungsu Kim†, Minho Hwang†"
            publisher: "Medical Image Computing and Computer Assisted Intervention (MICCAI) [Top Medical AI Conference] - 2025.05"
            note: "Co-First Author, Early Accepted paper [top 9%]"
            featuredLink:
              enable: true
              name: "read paper"
              url: "https://papers.miccai.org/miccai-2025/paper/3740_paper.pdf" # "https://arxiv.org/pdf/2503.01794"
            content: "In this paper, we propose a simple yet effective method to improve the normal detection confidence of radiology CLIP models. Our method, OFF-CLIP, automatically adjusts the off-diagonal term of the CLIP loss function to enhance the model’s ability to distinguish normal from abnormal images."
        
      - company: "Domestic Conference"
        publications:
          - job: "A Study on the Trends of Adaptive Deep Brain Stimulation in Parkinson's Disease"
            author: "<ins>Chanyu Moon</ins>, Ji-Woong Choi†"
            publisher: "한국통신학회 - 2025.02"
            note: "First Author,Oral presentation conducted at DGIST special session"
            featuredLink:
              enable: true
              name: "read paper"
              url: "https://www.dbpia.co.kr/pdf/pdfView.do?nodeId=NODE12132791"
            content: "파킨슨병(Parkinson’s disease; PD) 환자의 증상 완화법인 개방형 뇌 심부 자극(Open-loop Deep Brain Stimulation; DBS)의 한계를 극복하기 위해 적응형 뇌 심부 자극(adaptive Deep Brain Stimulation; aDBS)이 도입되어 각광받고 있다. 본 연구에서는 PD 환자에서의 aDBS의 입력 신호와 자극 파라미터 조절에 관한 최신 연구 동향을 소개한다." 

  # ───────────────────────────────────────────────────────────────────────────
  # 3-5) Education 섹션
  # ───────────────────────────────────────────────────────────────────────────
  education:
    enable: true
    # title: "Education"        # 필요하다면 커스텀 제목 지정 가능
    index: false               # 목록 페이지로 따로 빼지 않을 것인지 여부 (false면 메인 페이지에 섹션으로 나옴)
    items:
      - title: "M.S./Ph.D. Integrated Course"
        school:
          name: "Daegu Gyeongbuk Institute of Science and Technology (DGIST)"
          url: "https://www.dgist.ac.kr/"
        date: "2024.02 - present"
        
        content: |-
          Communication and Signal Processing Lab (CSP Lab)
          

      - title: "B.S. in Electrical Engineering and Computer Science"
        school:
          name: "Daegu Gyeongbuk Institute of Science and Technology (DGIST)"
          url: "https://www.dgist.ac.kr/"
        date: "2020.02 - 2024.02"
        content: |-
          Deans List (4.0 or higher out of 4.3)

        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"

      - title: "High School"
        school:
          name: "Busan Science High School"
          url: "https://school.busanedu.net/bss-h/main.do"
        date: "2017.03 - 2020.02"
        content: |-
          Club leader of Brain science club Neuro.
        
        featuredLink:
          enable: false
          url: "https://example.com"

  # ───────────────────────────────────────────────────────────────────────────
  # 3-6) Achievements 섹션
  # ───────────────────────────────────────────────────────────────────────────
  achievements:
    enable: false
    # title: "Achievements"      # 필요하다면 커스텀 제목
    items:
      - title: "Google Kickstart Runner"
        content: "I solved every problem with an optimal solution."
        url: "https://example.com"
        image: "/images/achievement.jpg"


  # ───────────────────────────────────────────────────────────────────────────
  # 3-7) Publication 섹션
  # ───────────────────────────────────────────────────────────────────────────
  projects:
    enable: false
    title: "title"    # 필요하다면 커스텀 제목 지정 가능
    items:
      - title: "project"
        date: "2025-01-01"
        image: "/images/IC1_offclip_figure.png"
        content: |-
          In this paper, we propose a simple yet effective method to improve the normal detection confidence of radiology CLIP models. 
          Our method, OFF-CLIP, automatically adjusts the off-diagonal term of the CLIP loss function to enhance the model's ability to distinguish normal from abnormal images.
        badges:
          - "Preprint"
        links:
          - icon: "fas fa-file-pdf"
            url: "https://arxiv.org/pdf/2503.01794.pdf"
          - icon: "fab fa-github"
            url: "https://github.com/off-clip/off-clip"


  # ───────────────────────────────────────────────────────────────────────────
  # 3-8) Contact 섹션
  # ───────────────────────────────────────────────────────────────────────────
  contact:
    enable: true
    # title: "Get in Touch"  # 필요하다면 커스텀 제목
    content: "My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!"
    btnName: "Mail me"
    btnLink: "mailto:moonchanyu@gmail.com"
    # 만약 Formspree 등 양식을 쓰려면 아래처럼 활성화
    # formspree:
    #   enable: true
    #   formId: "abcdefgh"      # ex) https://formspree.io/f/abcdefgh
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  # ───────────────────────────────────────────────────────────────────────────
  # 3-9) Footer 섹션
  # ───────────────────────────────────────────────────────────────────────────
  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: "Recent Posts"
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: "https://github.com/ChanyuMoon"
      linkedin: "https://www.linkedin.com/in/chanyu-moon-714727229/"
      # twitter: "https://twitter.com"
      # instagram: "https://instagram.com"
      # facebook: "https://facebook.com"

  # ───────────────────────────────────────────────────────────────────────────
  # 3-10) List / Single 페이지별 설정
  # ───────────────────────────────────────────────────────────────────────────
  listPages:
    disableFeaturedImage: false

  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # ───────────────────────────────────────────────────────────────────────────
  # 3-11) 다국어 번역(terms)이나 날짜 포맷
  # ───────────────────────────────────────────────────────────────────────────
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  # ───────────────────────────────────────────────────────────────────────────
  # 3-12) (필요 시) 커스텀 스크립트 추가
  # ───────────────────────────────────────────────────────────────────────────
  # customScripts:
  #   - |
  #     <script type="text/javascript">
  #       // 여기에 원하는 스크립트를 넣어 보세요
  #     </script>
  # hugo-profile 0.11+ 내장 옵션